version: "3.8"

services:
    app:
        build: .
        container_name: tradeasia-laravel
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: tradeasia_test
            DB_USERNAME: user
            DB_PASSWORD: password

    db:
        image: mysql:8
        container_name: tradeasia-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tradeasia_test
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
